features:
  id:
    - CustomerID
  categorical:
    - Gender
    - Subscription Type
    - Contract Length
  numerical:
    continuous:
      - Usage Frequency
      - Payment Delay
      - Total Spend
    discrete:
      - Age
      - Tenure
      - Support Calls
      - Last Interaction
target: Churn
